version: 0.2

env:
  variables:
    ECR_REPO_URI: "829710534710.dkr.ecr.ap-south-1.amazonaws.com/testecr"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REPO_URI
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t testecr .
      - docker tag testecr:latest $ECR_REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - printf '[{"name":"Mycluster","imageUri":"%s"}]' $ECR_REPO_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
